import { gemini, createAgent } from "@inngest/agent-kit";
import { inngest } from "./client";

export const testfunction = inngest.createFunction(
  { id: "oh shera function chal gya" },
  { event: "test/testfunction" },
  async ({ event }) => {
    // Create an agent specialized in code generation.
    const codeGenerator = createAgent({
      name: "code-generator",
      system: "You are an expert programmer. You write clean, efficient, and well-documented code in various programming languages.",
      // Configure the agent to use the Gemini model.
      model: gemini({ model: "gemini-1.5-flash"}),
    });

    // Use the agent to generate a code snippet based on the event data.
    const codeSnippet = await codeGenerator.run(
      `Generate a code snippet for the following task: ${event.data.value}`
    );

    // Log the generated code to the console for debugging.
    console.log("Generated Code:", codeSnippet);

    // Return a success message along with the code generated by the AI.
    return {
      message: `Successfully generated code for the task: "${event.data.value}"!`,
      generatedCode: codeSnippet,
    };
  },
);